name: adventofcode2023
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - containers

executables:
  day1:
    main: Day1.hs
    source-dirs: .
    ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
